name: Pvmfw Port Application

on:
  workflow_dispatch:
    inputs:
      opadUrl:
        description: 'OnePlus Pad Pro ROM Url'
        required: true
        type: string
      op13Url:
        description: 'OnePlus 13 ROM Url'
        required: true
        type: string

jobs:
  port:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install git+https://github.com/5ec1cff/payload-dumper

    - name: Download avbtool
      run: |
        curl -s https://android.googlesource.com/platform/external/avb/+/refs/heads/master/avbtool.py?format=TEXT | base64 -d > avbtool.py
        curl -s https://android.googlesource.com/platform/external/avb/+/refs/heads/master/test/data/testkey_rsa2048.pem?format=TEXT | base64 -d > testkey_rsa2048.pem
        curl -s https://android.googlesource.com/platform/external/avb/+/refs/heads/master/test/data/testkey_rsa4096.pem?format=TEXT | base64 -d > testkey_rsa4096.pem
        curl -s https://android.googlesource.com/platform/external/avb/+/refs/heads/master/test/data/testkey_rsa8192.pem?format=TEXT | base64 -d > testkey_rsa8192.pem

    - name: Run port script
      run: |
        bash run.sh
      env:
        OPAD_ROM_URL: ${{ inputs.opadUrl }}
        OP13_ROM_URL: ${{ inputs.op13Url }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: out/*.img
        if-no-files-found: error
